# Generated by Django 5.0.7 on 2024-08-02 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes_to_skips',
            new_name='votes_to_skip',
        ),
    ]
